<?php

declare(strict_types=1);

namespace Demo;

use Aol\Http\Attribute\BaseUrl;
use Aol\Http\Attribute\Get;
use Aol\Http\Attribute\Headers;
use Aol\Http\Attribute\Path;
use Aol\Http\Attribute\Query;
use Aol\Http\Response;
use Aol\Attribute\Retry;
use Aol\Attribute\Timeout;

/**
 * Retrofit-style declarative client for the GitHub REST API.
 *
 * The proxy generated by Http::fromInterface() does the wiring — no boilerplate.
 */
#[BaseUrl('https://api.github.com')]
#[Headers([
    'Accept' => 'application/vnd.github+json',
    'User-Agent' => 'php-aol-demo',
])]
interface GithubApi
{
    #[Get('/repos/{owner}/{repo}')]
    #[Retry(times: 2, backoff: 'exponential', delay: 0.25)]
    #[Timeout(8)]
    public function repo(#[Path] string $owner, #[Path] string $repo): GithubRepo;

    /**
     * Returns the raw response so we can read the GitHub-specific `X-Total-Count`
     * style headers that don't fit in the typed model.
     */
    #[Get('/search/repositories')]
    #[Timeout(8)]
    public function searchRepos(
        #[Query] string $q,
        #[Query] string $sort = 'stars',
        #[Query] int $per_page = 5,
    ): Response;
}
